# Generated by Django 4.0.4 on 2022-05-14 10:53

import Reserve.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('person_num', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('type_room', models.CharField(blank=True, choices=[('off su', 'Office Suite'), ('conf su', 'Conference Suite'), ('jnr su', 'Junior Suite'), ('vip su', 'VIP Suite'), ('fie su', 'Fiesta Suite'), ('sngl', 'Single Suite')], max_length=50, null=True)),
                ('request_user', models.TextField(blank=True, null=True)),
                ('offers', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('news', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('sms', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReservingHotel', to=settings.AUTH_USER_MODEL)),
                ('reserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReserveUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.ManyToManyField(related_name='wishlisttoresidence', to='Supplier.residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'db_table': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='Upcomming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ManyToManyField(related_name='upcommingtoreserve', to='Reserve.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcommingtocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upcomming',
                'verbose_name_plural': 'Upcommings',
                'db_table': 'upcomming',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ManyToManyField(related_name='historytoreserve', to='Reserve.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
                'db_table': 'History',
            },
        ),
    ]
