# Generated by Django 4.0.4 on 2022-05-08 07:08

import Reserve.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('person_num', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('type_room', models.CharField(blank=True, choices=[('off su', 'Office Suite'), ('conf su', 'Conference Suite'), ('jnr su', 'Junior Suite'), ('vip su', 'VIP Suite'), ('fie su', 'Fiesta Suite'), ('sngl', 'Single Suite')], max_length=50, null=True)),
                ('request_user', models.TextField(blank=True, null=True)),
                ('offers', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('news', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('sms', Reserve.models.CustomBooleanField(blank=True, default=0, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReservingHotel', to=settings.AUTH_USER_MODEL)),
                ('reserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReserveUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
