# Generated by Django 4.0.4 on 2022-04-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(verbose_name='address')),
                ('img', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('type', models.CharField(choices=[('lux', 'lux hotel'), ('h', 'hotel'), ('gh', 'guesthouse')], max_length=10)),
                ('tag', models.CharField(choices=[('res', 'Restaurant'), ('lux', 'lux'), ('sh', 'Sports hall')], max_length=10)),
                ('service_hours_start', models.IntegerField()),
                ('service_hours_end', models.IntegerField()),
                ('max_reserve', models.IntegerField()),
                ('detail', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_img1', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('room_img2', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('room_img3', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('numberـofـbed', models.IntegerField()),
                ('state', models.CharField(choices=[('F', 'Full'), ('E', 'Empty')], max_length=10)),
                ('faciliti', models.CharField(choices=[('lux', 'lux'), ('re', 'Refrigerator'), ('so', 'Sofa')], max_length=10)),
                ('price', models.BigIntegerField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResidenceRoom', to='Supplier.residence')),
            ],
        ),
    ]
