# Generated by Django 4.0.4 on 2022-04-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='residenceTOprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='res_name')),
                ('last_login', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.TextField(verbose_name='address')),
                ('img', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('type', models.CharField(choices=[('lux', 'lux hotel'), ('h', 'hotel'), ('gh', 'guesthouse')], max_length=10)),
                ('tag', models.CharField(blank=True, choices=[('res', 'Restaurant'), ('lux', 'lux'), ('sh', 'Sports hall')], max_length=10, null=True)),
                ('service_hours_start', models.IntegerField()),
                ('service_hours_end', models.IntegerField()),
                ('max_reserve', models.IntegerField()),
                ('detail', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'residiance',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_img1', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('room_img2', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('room_img3', models.ImageField(blank=True, null=True, upload_to='supplier/')),
                ('numberـofـbed', models.IntegerField()),
                ('state', models.CharField(choices=[('F', 'Full'), ('E', 'Empty')], max_length=10)),
                ('faciliti', models.CharField(choices=[('lux', 'lux'), ('re', 'Refrigerator'), ('so', 'Sofa')], max_length=10)),
                ('price', models.BigIntegerField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Residence_Room', to='Supplier.residence')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
