# Generated by Django 4.0.4 on 2022-05-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_alter_service_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuTOroom', to='Supplier.residence'),
        ),
    ]
