# Generated by Django 4.0.4 on 2022-05-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_restaurantmenu_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
