# Generated by Django 4.0.4 on 2022-05-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_alter_restaurantmenu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='residenceindooralbum',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inTOmenu', to='Supplier.restaurantmenu'),
        ),
        migrations.AddField(
            model_name='residenceindooralbum',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inTOservice', to='Supplier.service'),
        ),
        migrations.AddField(
            model_name='residenceoutdooralbum',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outTOmenu', to='Supplier.restaurantmenu'),
        ),
        migrations.AddField(
            model_name='residenceoutdooralbum',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outTOservice', to='Supplier.service'),
        ),
        migrations.AlterField(
            model_name='residenceindooralbum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residenceindooralbum',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inTOroom', to='Supplier.residence'),
        ),
        migrations.AlterField(
            model_name='residenceoutdooralbum',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outTOroom', to='Supplier.residence'),
        ),
    ]
