# Generated by Django 4.0.4 on 2022-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_residenceindooralbum_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residenceoutdooralbum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
