# Generated by Django 4.0.4 on 2022-05-07 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('person_num', models.IntegerField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ReserveRoom', to='Supplier.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ReserveUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ManyToManyField(to='Reservation.reserve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='Upcomming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ManyToManyField(to='Reservation.reserve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcommingtocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upcomming',
                'verbose_name_plural': 'Upcommings',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ManyToManyField(to='Reservation.reserve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytocustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
            },
        ),
    ]
